version: '3.9'

services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    container_name: angular-mangas-world
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./dist:/usr/share/nginx/html:ro
